- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/internal/AttributeValueMarshaller.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/internal/AttributeValueMarshallerTest.java
Add support for new AttributeValue data types: NULL, BOOL, List, and Map
> Support new datatypes

- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/TransformerHolisticTests.java
This adds new holistic tests for using WrappedMaterialsProvider with a symmetric AES wrapping key in AES KeyWrap mode.
> Add Holistic tests for WrappedMaterialsProvider using AESWrap

- README.md
- pom.xml
Description of changes: Documentation changes to update hyperlinks, and minor version bump.
> Move repository from awslabs to aws.

- README.md
- pom.xml
> Bump patch version to 1.11.2

- README.md
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java
Update documentation and logging to indicate that `SaveBehavior.PUT` is also safe.
> Update documents to indicate that SaveBehavior.PUT is also safe

- .travis.yml
Enables testing for OpenJDK11 in Travis
> Add CI for OpenJDK11

- CHANGELOG.md
This starts a changelog, which follows the same format as the encryption sdk
for java.
(For release of 1.2.0)
> Add CHANGELOG to dynamodb encryption client for java

- pom.xml
> Update checkstyle plugin version

- sdk1/pom.xml
*Issue #, if available:* #98
Move to new sonatype endpoint.
This does not require any changes by our consumers.
It is solely a publishing change.
> Move to new sonatype endpoint. #98

- CHANGELOG.md
- sdk1/pom.xml
> Prepare for 1.14.0 release

- CHANGELOG.md
- README.md
Fix 1.14.0 release date and in README
> Fix 1.14.0 release date and in README

- sdk1/pom.xml
> Add url for sdk1

- README.md
> Update readme to mention 1.14.1

- pom.xml
- sdk1/pom.xml
- sdk2/pom.xml
Updates checkstyle dependencies to newest versions.
> Update checkstyle dependencies

- CONTRIBUTING.md
- README.md
*Issue #, if available:* n/a
*Description of changes:* Add missing `CONTRIBUTING.md` as well as breadcrumb for security reporting to `README.md`.
> chore: Add CONTRIBUTING.md and security reports.

- .travis.yml
> chore: Remove Travis CI

- CHANGELOG.md
- README.md
- examples/pom.xml
- pom.xml
- sdk1/pom.xml
> Bump version

- CHANGELOG.md
> Fix release date on 1.15.1

- sdk1/pom.xml
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/TransformerHolisticIT.java
*Issue #, if available:* Update AWS SDK dependencies
*Description of changes:* 
> chore(deps): update dependencies

- .github/dependabot.yml
- .gitignore
Adds dependabot.yml file in order to keep our dependencies updated.
> chore: enable dependabot in our active branches and update gitignore

- cfn/DDB-EC-Java.yml
- codebuild/release/release-prod.yml
- codebuild/release/settings.xml
- sdk1/pom.xml
I'll wait until #1156 is in main before merging this, so the CFN changes are clearer.
> chore(release): Migrate release to Central Portal
