- pom.xml
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/MostRecentProviderTests.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStoreTests.java
Fix bad usage of DynamoDB mock by replacing it with DynamoDB Local. Also updated the aws-java-sdk version.
> Fix the build

- pom.xml
use BOM to avoid downloading all aws dependencies, as described in http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-using-maven.html
> use AWS BOM

- pom.xml
http endpoint will be disabled soon. We have to use https
> Update dynamodb-local repo URL

- pom.xml
Changes the listed dependency of this package to aws-java-sdk version 1.11.315 which gives us the new client builders.
> Consume latest version of AWS SDK. 1.11.315

- README.md
- examples/com/amazonaws/examples/AwsKmsEncryptedObject.java
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/TransformerHolisticTests.java
- src/test/java/com/amazonaws/services/dynamodbv2/testing/FakeParameters.java
This is in support of issue #42 
This adds basic documentation to `AttributeEncryptor` and related example code highlighting the importance of using `SaveBehavior.CLOBBER`.
All existing tests pass. Some of the existing tests did not properly set this configuration and resulted in proper warnings during the test run:
SEVERE: Use of AttributeEncryptor without SaveBehavior.CLOBBER is an error and may result in data-corruption. This occured while trying to save class com.amazonaws.services.dynamodbv2.testing.types.Mixed
> Update documentation and warnings related to SaveBehavior.

- VERSIONING.rst
This is a public statement of our official versioning policy and philosophy.
> Statement of our versioning policy and philosophy

- .github/PULL_REQUEST_TEMPLATE.md
- VERSIONING.rst
Included in this PR:
* Adding our PR template
* Adding explicit callout of our dependency version change behavior
* Adding Z version change notice for upcoming breaking changes, where possible
* Try to simplify some language in `VERSIONING.rst`
> Cleanup for pull requests and versioning policy.

- README.md
- pom.xml
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptor.java
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStore.java
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/internal/LRUCache.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptorTest.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStoreTests.java
This pull-request is a roll-up to synchronize functionality and release several minor features.
**Together these changes are sufficiently important that a minor version bump to 1.12.0 is included in this PR.**
Changes:
* Minor version change to 1.12.0
* Dependency versions are updated
* Added `MetaStore.replicate` to make it easier to copy data-keys from one MetaStore to another
* Better support for non-standard JCA providers
* Fixed thread-safety issue in LRUCache
> Feature merge

- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptorTest.java
Issue #32 
This change causes the `AttributeEncryptor` to reject any unsafe use of `SaveBehavior` other than `PUT` or `CLOBBER` with a `DynamoDBMappingException`. This falls under the (as yet unreleased) minor version bump to 1.12.0 from PR #47 .
> Force use of SaveBehavior.PUT or SaveBehavior.CLOBBER. Issue #32

- pom.xml
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/TransformerHolisticTests.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptorTest.java
- src/test/java/com/amazonaws/services/dynamodbv2/testing/AttrMatcher.java
These new tests explicitly cover encryption & decryption of non-original DynamoDB data-types as well as ensure that optimistic locking works properly with `SaveBehavior.PUT`. To support `SaveBehavior.PUT` this change also updates the dependency on aws-sdk-java-bom to the current version `1.11.434`.
> New tests to cover more data types and optimistic locking. Also increments SDK dependency.

- .travis.yml
- README.md
This updates the readme to specify the JDK version used by the project to be at least JDK8. Let me know if we need JDK7 builds after all, my opinion is just based on what is inside the pom.xml and other build configurations.
Tested JDK7 using Travis - test failed, due to "[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project aws-dynamodb-encryption-java: Fatal error compiling: invalid target release: 1.8 -> [Help 1]"
Updated .travis.yml to JDK8 and tested on Travis - tests passed
> Update README to specify JDK8 or greater, and update .travis.yml to use JDK8

- examples/com/amazonaws/examples/AwsKmsEncryptedObject.java
- examples/com/amazonaws/examples/EncryptionContextOverridesWithDynamoDBMapper.java
- pom.xml
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptor.java
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/utils/EncryptionContextOperators.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptorTest.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/utils/EncryptionContextOperatorsTest.java
There are people asking for overrides, and it would be better if they didn't
need to wait for longer term, internal refactors before they are able to use
overrides. This adds optional operators that give the client the last say on the
EncryptionContext's value.
Note: I haven't tested the example, since I didn't figure out a way to run them.
How are we running example code? If we don't have a suggested way yet, I can
figure something out and document it.
> Add support for EncryptionContext overrides to the DynamoDBEncryptor

- pom.xml
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptorTest.java
This replaces calls to assertNotEquals to use hamcrest matchers. Hamcrest matchers are better because they separate assertion from the predicate being asserted.
> Refactor DynamoDBEncryptorTests to use hamcrest

- .gitignore
- pom.xml
Modify the copy-dependencies plugin configuration to copy dlls, dylibs,
and .so's to the test-lib directory so that tests can be run on more platforms.
Switch the phase to test-compile, since the libs aren't a compilation
requirement.
Update the maven surefire dependency and disable the system classloader for
tests for this bug in some versions of the JDK (like on ubuntu right now):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911925
Tested on Ubuntu and OSX, not sure whether Windows works since I didn't try but it should.
> Add support for running tests on OSX and Windows

- pom.xml
Add the maven failsafe plugin for running integration tests. Maven failsafe is
like maven surefire, but it ensures that various cleanup is called when
integration tests fail. It hooks into the existing release workflow, so
integration tests run before install or release.
The integration tests may be run through $mvn integration-test
> Add maven failsafe plugin for running integration tests.

- .travis.yml
- pom.xml
Add JaCoCo which generates jacoco.exec files and xml reports of code coverage. Add Codecov's hosted bash script for uploading the reports on travis. More importantly, fix travis to run tests.
> Add JaCoCo and Codecov and fix travis to run tests

- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProvider.java
- src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStore.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProviderTest.java
- src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStoreTests.java
Failed check from Travis is expected because JDK11 recently stopped working on Travis (nothing to do with our code).
This is a near direct copy of DirectKMS and MetaStore. Commit 4e682ea is a direct copy of the internal metastore and DirectKMSMaterialProvider. There will probably need to be a minor update to this to get it to work with testng.
> Add ExtraDataSupplier to Metastore, and support for overriding KMS requests in DirectKMSMaterialProvider

- pom.xml
This adds connection metadata, which helps with tools that need to know where to
retrieve the source code of jars.
> Add SCM connection metadata to pom.xml

- ddej-build-tools/pom.xml
- ddej-build-tools/src/main/resources/software/amazon/cryptools/ddej-build-tools/checkstyle/checkstyle-suppressions.xml
- ddej-build-tools/src/main/resources/software/amazon/cryptools/ddej-build-tools/checkstyle/checkstyle.xml
- examples/com/amazonaws/examples/AsymmetricEncryptedItem.java
- examples/com/amazonaws/examples/AwsKmsEncryptedItem.java
- examples/com/amazonaws/examples/AwsKmsEncryptedObject.java
- examples/com/amazonaws/examples/EncryptionContextOverridesWithDynamoDBMapper.java
- examples/com/amazonaws/examples/MostRecentEncryptedItem.java
- examples/com/amazonaws/examples/SymmetricEncryptedItem.java
- pom.xml
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/utils/EncryptionContextOperators.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/internal/Utils.java
Before, we didn't have any automated checks for license headers. This adds a check that fails the build if there is a missing license.
> Add Checkstyle with License Check to Build, and add missing headers

- .travis.yml
Oracle JDK8 is broken on travis through no fault of the client code. Removing so that
we can commit to this repository without continuously failing CI.
> Remove oraclejdk8 CI

- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotEncrypt.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotTouch.java
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptorTest.java
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/testing/types/DoNotEncryptField.java
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/testing/types/DoNotTouchField.java
https://github.com/aws/aws-dynamodb-encryption-java/issues/94
Inspect potential field level annotations using StandardAnnotationMaps when deciding whether to touch/encrypt an attribute
> Allow DoNotEncrypt/DoNotTouch field level annotations

- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProvider.java
- sdk2/src/main/java/software/amazon/cryptools/dynamodbencryptionclientsdk2/encryption/providers/DirectKmsMaterialsProvider.java
We have a need to provide our own encryption context for calls to KMS. This change makes the `populateKmsEcFromEc` method of `DirectKmsMaterialsProvider` protected so we can override it.
> Allow overriding KMS encryption context.

- sdk1/pom.xml
Moving to the aws.oss.sonatype endpoint. Needed to do some testing in
advance of the 1.4.1 patch release.
> Update snapshot URL

- sdk1/pom.xml
- sdk2/pom.xml
1.14.0 fails since
software.amazon.cryptools:dynamodbencryptionclient-pom isn't deployed to
maven (but it passes locally, if you've installed it into your local
maven repository).
For context, we originally split the maven module up into a shared
package, an sdk1 package and an sdk2 package, and intended to have a
large amount of reuse. That wound up not happening: sdk2 is entirely
self-contained.
Although there's some duplication in between the build logic between
sdk1 and sdk2, it's not worth the mental overhead of dealing with a
parent and aggregator pom.
The only functional change from doing this is that it isn't necessary to deploy the dynamodbencryptionclient-pom. It is still possible to run all tests / compile everything from the root module.
*Description …
> Remove parent dependency from sdk1, sdk2

- CHANGELOG.md
1.14.0 can't be consumed by most clients, since it has a dependency that
isn't available in mavenCentral (the dependency is the parent pom in
this repository, if you are curious). If you were thinking of using
1.14.0, use 1.14.1 instead.
> Update changelog for 1.14.1 (Patch)

- sdk1/pom.xml
> Bump version to 1.14.1 in pom.xml

- sdk1/pom.xml
Newer versions of gpg fail signing with the following error message:
`gpg: signing failed: Inappropriate ioctl for device`
This can be fixed by explicitly telling gpg to ask the caller for the passphrase/pin, rather than letting to attempt to query for it out of band to a human directly (which doesn't exist). On the command line it is done by adding the arguments `--pinentry-mode loopback`. This change tells maven to pass in these new arguments.
This has been tested with as part of building, signing and releasing version 1.6.1 of the aws-encryption-sdk-java.
> Fix for new versions of gpg

- CHANGELOG.md
- pom.xml
*Issue #, if available:* #118 
*Description of changes:* Updating Bouncy Castle to the latest version (1.65)
> Upgrade Bouncy Castle from 1.61 to 1.65

- .travis.yml
- buildspec.yml
- codebuild/codecov.sh
- codebuild/corretto11.yml
- codebuild/corretto8.yml
- codebuild/openjdk11.yml
- codebuild/openjdk8.yml
Adding buildspec to batch build
multiple JDK environments
* corretto8
* corretto11
* openjdk8
* openjdk11
> chore: Add AWS CodeBuild buildspec

- codebuild/codecov.sh
- codebuild/corretto11.yml
- codebuild/corretto8.yml
- codebuild/openjdk11.yml
- codebuild/openjdk8.yml
> chore: Remove codecov from CI

- CHANGELOG.md
> Fix release date of 2.0.1 in changelog

- .gitignore
- README.md
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotEncrypt.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotTouch.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptor.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBSigner.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/HandleUnknownAttributes.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/TableAadOverride.java
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/TransformerHolisticIT.java
*Description of changes:* Add documentation pointers to the data model migration guide to improve discovery for customers. Opportunistically fix a couple of Javadoc issues and update `.gitignore`.
> fix: Data model migration doc breadcrumb.

- sdk1/pom.xml
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProvider.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/internal/Utils.java
- sdk1/src/main/resources/project.properties
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProviderTest.java
Update user agent string to show the correct DDBEC library version. Previously, we had a) never updated the version string of our library from `1.0`, and b) were needlessly including the version of the AWS Java SDK (this is already added as part of the user agent string by the SDK).
Rather than adding another place we have to hardcode the correct version, I'm pulling it from pom.xml.
I've also updated the format of our appended string to more closely match what we do in Python DDBEC and Java ESDK.
*Testing:*
This gives us a full user agent string like the following:
`aws-sdk-java/1.11.460 Mac_OS_X/10.15.7 OpenJDK_64-Bit_Server_VM/11.0.5+10-b520.38 java/11.0.5 DynamodbEncryptionSdkJava/2.0.1`
(First section is generated by AWS SDK, last section is ours)
By …
> fix: Update user agent string to correctly reflect version

- examples/src/main/java/com/amazonaws/examples/AwsKmsMultiRegionKey.java
- examples/src/test/java/com/amazonaws/examples/AwsKmsMultiRegionKeyIT.java
- examples/src/test/java/com/amazonaws/examples/TestUtils.java
An example illustrating how to use KMS Multi-Region keys with DDBEC
> chore: Add examples for MRKs

- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
- codebuild/release/settings.xml
- codebuild/release/validate-prod.yml
- codebuild/release/validate-staging.yml
- examples/pom.xml
*Issue #, if available:* N/A
*Description of changes:* Test Release and Prod Release will validate a release on 4 different Java SDKs 
I highly recommend a Squash and Merge approach.
Final commit message should be: `ci: test against multiple JDKs`
> ci: create release builds that validate on multiple JDKs

- sdk1/pom.xml
- sdk1/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/TransformerHolisticIT.java
*Issue #, if available:* Upgrade dependencies. (sdk 1.11 -> 1.12 requires a new version of jackson to be imported, which has a slightly breaking change in the ObjectMapper)
*Description of changes:* `mvn install`
> chore: Upgrade sdk to 1.12

- CHANGELOG.md
- README.md
- examples/pom.xml
- pom.xml
Updating CHANGELOG for version bump 2.0.2
> bump version, update CHANGELOG for v2.0.2

- CHANGELOG.md
- buildspec.yml
- codebuild/release/release-prod.yml
- codebuild/release/release-staging.yml
- codebuild/release/settings.xml
- codebuild/release/validate-prod.yml
- codebuild/release/validate-staging.yml
- codebuild/static-analysis.yml
> ci: backport codebuild release from 2.x

- SUPPORT_POLICY.rst
The support policy from master was never added to the 1.x branch. This copies it over ahead of the impending 1.x end-of-support release.
> chore: Copy support policy to 1.x branch

- CHANGELOG.md
- README.md
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/AttributeEncryptor.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotEncrypt.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DoNotTouch.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBEncryptor.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/DynamoDBSigner.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/HandleUnknownAttributes.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/TableAadOverride.java
*Issue #, if available:* As part of the new Database Encryption release, the docs for DDBEC have moved.
> fix(docs): Update AWS Doc URLs

- README.md
Add links to DB-ESDK in README
> fix: Add DB-ESDK 3.x section to README

- examples/src/main/java/com/amazonaws/examples/EncryptionContextOverridesWithDynamoDBMapper.java
- examples/src/test/java/com/amazonaws/examples/EncryptionContextOverridesWithDynamoDBMapperIT.java
- sdk1/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/utils/EncryptionContextOperators.java
The names in `overrideEncryptionContextTableName`
are relative to the code and not the customer using the code.
This updates these names and docs
to reflect the intuition customers have
when dealing with two different table names.
Overriding #754 
> feat: Update overrideEncryptionContextTableName
